
use master 
go

CREATE DATABASE BDRENIEC
GO
SP_HELPDB BDRENIEC

CREATE DATABASE BDRENIEC
ON(NAME=BDRENIEC_DATA,
FILENAME='D:\DATOS_RENIEC\BDRENIEC_DATA.mdf',
SIZE=20,MAXSIZE=100,FILEGROWTH=4)
LOG ON(NAME=BDRENIEC_LOG,FILENAME='D:\DATOS_RENIEC\BDRENIEC_DATA.Ldf',
SIZE=10,MAXSIZE=150,FILEGROWTH=10%)
GO
SP_HELPDB BDRENIEC


